function toggleMenu(){const x=document.querySelector('.links');if(x)x.classList.toggle('open')}
function show(id,text){const x=document.getElementById(id);if(!x)return;x.style.display='block';x.innerHTML='<b>Résultat :</b> '+text}
const num=id=>{const e=document.getElementById(id);return e?parseFloat(e.value)||0:0};
function calcVolume(){const l=num('l'),b=num('b'),h=num('h');show('r',(l*b*h).toFixed(2)+' m³ de béton')}
function calcSteel(){const d=num('d'),l=num('sl');show('rs',((d*d/162)*l).toFixed(2)+' kg d’acier (formule d²/162)')}
function calcArea(){show('ra',(num('al')*num('ab')).toFixed(2)+' m²')}
function calcBeam(){const L=num('beamSpan'),ratio=num('beamRatio');if(L<=0||ratio<=0)return show('rb','Veuillez saisir une portée et un rapport positifs.');show('rb','Hauteur indicative ≈ <strong>'+(L*100/ratio).toFixed(1)+' cm</strong><br><small>Prédimensionnement uniquement : vérification réglementaire obligatoire.</small>')}
function calcSlab(){const L=num('slabSpan'),ratio=num('slabRatio');if(L<=0||ratio<=0)return show('rd','Veuillez saisir une portée et un rapport positifs.');show('rd','Épaisseur indicative ≈ <strong>'+(L*100/ratio).toFixed(1)+' cm</strong><br><small>À confirmer par le calcul ELU/ELS.</small>')}
function calcFooting(){const N=num('loadN'),q=num('soilQ');if(N<=0||q<=0)return show('rf','Veuillez saisir N et la pression de référence.');const s=N/q;show('rf','Surface théorique ≈ <strong>'+s.toFixed(2)+' m²</strong><br>Semelle carrée équivalente ≈ <strong>'+Math.sqrt(s).toFixed(2)+' × '+Math.sqrt(s).toFixed(2)+' m</strong>')}
function calcSlabLoad(){const e=num('thick');if(e<=0)return show('rsl','Veuillez saisir une épaisseur positive.');show('rsl','Poids propre indicatif ≈ <strong>'+(e/100*25).toFixed(2)+' kN/m²</strong>')}
function calcExc(){const v=num('excL')*num('excB')*num('excH');show('re','Volume géométrique ≈ <strong>'+v.toFixed(2)+' m³</strong>')}
function filterCards(cat,btn){document.querySelectorAll('.filters button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');document.querySelectorAll('[data-cat]').forEach(x=>x.style.display=(cat==='all'||x.dataset.cat.includes(cat))?'':'none')}
function searchResources(){const s=document.getElementById('search');if(!s)return;const q=s.value.toLowerCase();document.querySelectorAll('[data-search]').forEach(x=>x.style.display=x.innerText.toLowerCase().includes(q)?'':'none')}
document.addEventListener('DOMContentLoaded',function(){const pages={'Poutre BA simplement appuyée':'exercice-poutre-ba.html','Dalle pleine unidirectionnelle':'exercice-dalle-pleine.html','Poteau en béton armé':'exercice-poteau-ba.html','Semelle isolée':'exercice-semelle-isolee.html','RDM — Poutre et charges':'exercice-rdm-poutre.html','Géotechnique — Pression du sol':'exercice-geotechnique-sol.html','Escalier en béton armé':'exercice-escalier-ba.html','Mur de soutènement':'exercice-mur-soutenement.html'};document.querySelectorAll('.exercise-card').forEach(function(card){const title=card.querySelector('h3'),solution=card.querySelector('.solution');if(!title||!solution)return;const href=pages[title.textContent.trim()];if(href&&!solution.querySelector('.full-exercise-link')){const a=document.createElement('a');a.href=href;a.className='btn full-exercise-link';a.style.marginTop='16px';a.textContent='📘 Ouvrir l’exercice complet étape par étape';solution.appendChild(a)}});const badge=document.querySelector('.progress-badge');if(badge)badge.innerHTML='8 exercices<br><strong>corrigés</strong>'});